#ifndef CONFIG_H
#define CONFIG_H

#define CHUNK_SIZE 16
#define LOADED_WORLD_WIDTH 32
#define LOADED_WORLD_HEIGHT 32
#define LOADED_WORLD_CENTER_X (LOADED_WORLD_WIDTH / 2)
#define LOADED_WORLD_CENTER_Y (LOADED_WORLD_HEIGHT / 2)
#define HASH_TABLE_BUCKETS 16384
#define HASH_TABLE_BUCKET_SIZE 8
#define OLD_RENDERER 0

#endif // CONFIG_H